//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PvTerrenos.WSpvt {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://serviciodeconsultas.hol.es/webservice/", ConfigurationName="WSpvt.PVTPortType")]
    public interface PVTPortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string login(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/login", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> loginAsync(string usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string registraUsuario(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraUsuario", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> registraUsuarioAsync(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listarUsuarios", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string listarUsuarios(string id_sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listarUsuarios", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> listarUsuariosAsync(string id_sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/usuarioUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string usuarioUpdate(string id_sesion, string id_usuario, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/usuarioUpdate", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> usuarioUpdateAsync(string id_sesion, string id_usuario, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/usuarioChangePasswor" +
            "d", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string usuarioChangePassword([System.ServiceModel.MessageParameterAttribute(Name="id-sesion")] [System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion, string id_usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/usuarioChangePasswor" +
            "d", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> usuarioChangePasswordAsync([System.ServiceModel.MessageParameterAttribute(Name="id-sesion")] [System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion, string id_usuario, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getPerfilUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getPerfilUsuario([System.ServiceModel.MessageParameterAttribute(Name="id-sesion")] [System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getPerfilUsuario", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getPerfilUsuarioAsync([System.ServiceModel.MessageParameterAttribute(Name="id-sesion")] [System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarUsuarioPor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string buscarUsuarioPor([System.ServiceModel.MessageParameterAttribute(Name="id-sesion")] [System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarUsuarioPor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> buscarUsuarioPorAsync([System.ServiceModel.MessageParameterAttribute(Name="id-sesion")] [System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraComprador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string registraComprador(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraComprador", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> registraCompradorAsync(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateComprador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string updateComprador(string id_sesion, string id_comprador, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateComprador", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> updateCompradorAsync(string id_sesion, string id_comprador, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getComprador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getComprador(string id_sesion, string id_comprador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getComprador", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getCompradorAsync(string id_sesion, string id_comprador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listarCompradores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string listarCompradores(string id_sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listarCompradores", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> listarCompradoresAsync(string id_sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarCompradorPor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string buscarCompradorPor(string id_sesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarCompradorPor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> buscarCompradorPorAsync(string id_sesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/eliminaComprador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string eliminaComprador(string id_sesion, string id_comprador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/eliminaComprador", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> eliminaCompradorAsync(string id_sesion, string id_comprador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraventa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string registraventa(string id_sesion, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraventa", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> registraventaAsync(string id_sesion, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string updateVenta(string id_sesion, string id_venta, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateVenta", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> updateVentaAsync(string id_sesion, string id_venta, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listaVentas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string listaVentas(string id_sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listaVentas", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> listaVentasAsync(string id_sesion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getComision", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getComision(string id_sesion, string venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getComision", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getComisionAsync(string id_sesion, string venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/setComision", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string setComision(string id_sesion, string venta, string comicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/setComision", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> setComisionAsync(string id_sesion, string venta, string comicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getVenta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string getVenta(string id_sesion, string id_venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getVenta", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getVentaAsync(string id_sesion, string id_venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarVentaPor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string buscarVentaPor(string id_sesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarVentaPor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> buscarVentaPorAsync(string id_sesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string registraLote(string id_sesion, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraLote", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> registraLoteAsync(string id_sesion, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string updateLote(string id_sesion, string id_lote, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateLote", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> updateLoteAsync(string id_sesion, string id_lote, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/eliminaLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string eliminaLote(string id_sesion, string id_lote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/eliminaLote", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> eliminaLoteAsync(string id_sesion, string id_lote);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscaLotePor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string buscaLotePor(string id_sesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscaLotePor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> buscaLotePorAsync(string id_sesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/hacerPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string hacerPago(string id_sesion, string id_venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/hacerPago", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> hacerPagoAsync(string id_sesion, string id_venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/cancelarPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string cancelarPago(string id_sesion, string id_venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/cancelarPago", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> cancelarPagoAsync(string id_sesion, string id_venta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarPagos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string buscarPagos(string id_sesion, string modo, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarPagos", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> buscarPagosAsync(string id_sesion, string modo, string valor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PVTPortTypeChannel : PvTerrenos.WSpvt.PVTPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PVTPortTypeClient : System.ServiceModel.ClientBase<PvTerrenos.WSpvt.PVTPortType>, PvTerrenos.WSpvt.PVTPortType {
        
        public PVTPortTypeClient() {
        }
        
        public PVTPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PVTPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PVTPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PVTPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string login(string usuario, string password) {
            return base.Channel.login(usuario, password);
        }
        
        public System.Threading.Tasks.Task<string> loginAsync(string usuario, string password) {
            return base.Channel.loginAsync(usuario, password);
        }
        
        public string registraUsuario(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email, string password) {
            return base.Channel.registraUsuario(id_sesion, nombre, apellidoPaterno, apellidoMaterno, tipo, email, password);
        }
        
        public System.Threading.Tasks.Task<string> registraUsuarioAsync(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email, string password) {
            return base.Channel.registraUsuarioAsync(id_sesion, nombre, apellidoPaterno, apellidoMaterno, tipo, email, password);
        }
        
        public string listarUsuarios(string id_sesion) {
            return base.Channel.listarUsuarios(id_sesion);
        }
        
        public System.Threading.Tasks.Task<string> listarUsuariosAsync(string id_sesion) {
            return base.Channel.listarUsuariosAsync(id_sesion);
        }
        
        public string usuarioUpdate(string id_sesion, string id_usuario, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email) {
            return base.Channel.usuarioUpdate(id_sesion, id_usuario, nombre, apellidoPaterno, apellidoMaterno, tipo, email);
        }
        
        public System.Threading.Tasks.Task<string> usuarioUpdateAsync(string id_sesion, string id_usuario, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email) {
            return base.Channel.usuarioUpdateAsync(id_sesion, id_usuario, nombre, apellidoPaterno, apellidoMaterno, tipo, email);
        }
        
        public string usuarioChangePassword(string idsesion, string id_usuario, string password) {
            return base.Channel.usuarioChangePassword(idsesion, id_usuario, password);
        }
        
        public System.Threading.Tasks.Task<string> usuarioChangePasswordAsync(string idsesion, string id_usuario, string password) {
            return base.Channel.usuarioChangePasswordAsync(idsesion, id_usuario, password);
        }
        
        public string getPerfilUsuario(string idsesion) {
            return base.Channel.getPerfilUsuario(idsesion);
        }
        
        public System.Threading.Tasks.Task<string> getPerfilUsuarioAsync(string idsesion) {
            return base.Channel.getPerfilUsuarioAsync(idsesion);
        }
        
        public string buscarUsuarioPor(string idsesion, string modo, string valor) {
            return base.Channel.buscarUsuarioPor(idsesion, modo, valor);
        }
        
        public System.Threading.Tasks.Task<string> buscarUsuarioPorAsync(string idsesion, string modo, string valor) {
            return base.Channel.buscarUsuarioPorAsync(idsesion, modo, valor);
        }
        
        public string registraComprador(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio) {
            return base.Channel.registraComprador(id_sesion, nombre, apellidoPaterno, apellidoMaterno, domicilio, recidencia, e_civil, ocupacion, beneficiario, tels, colonia, estado, municipio);
        }
        
        public System.Threading.Tasks.Task<string> registraCompradorAsync(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio) {
            return base.Channel.registraCompradorAsync(id_sesion, nombre, apellidoPaterno, apellidoMaterno, domicilio, recidencia, e_civil, ocupacion, beneficiario, tels, colonia, estado, municipio);
        }
        
        public string updateComprador(string id_sesion, string id_comprador, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio) {
            return base.Channel.updateComprador(id_sesion, id_comprador, nombre, apellidoPaterno, apellidoMaterno, domicilio, recidencia, e_civil, ocupacion, beneficiario, tels, colonia, estado, municipio);
        }
        
        public System.Threading.Tasks.Task<string> updateCompradorAsync(string id_sesion, string id_comprador, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio) {
            return base.Channel.updateCompradorAsync(id_sesion, id_comprador, nombre, apellidoPaterno, apellidoMaterno, domicilio, recidencia, e_civil, ocupacion, beneficiario, tels, colonia, estado, municipio);
        }
        
        public string getComprador(string id_sesion, string id_comprador) {
            return base.Channel.getComprador(id_sesion, id_comprador);
        }
        
        public System.Threading.Tasks.Task<string> getCompradorAsync(string id_sesion, string id_comprador) {
            return base.Channel.getCompradorAsync(id_sesion, id_comprador);
        }
        
        public string listarCompradores(string id_sesion) {
            return base.Channel.listarCompradores(id_sesion);
        }
        
        public System.Threading.Tasks.Task<string> listarCompradoresAsync(string id_sesion) {
            return base.Channel.listarCompradoresAsync(id_sesion);
        }
        
        public string buscarCompradorPor(string id_sesion, string modo, string valor) {
            return base.Channel.buscarCompradorPor(id_sesion, modo, valor);
        }
        
        public System.Threading.Tasks.Task<string> buscarCompradorPorAsync(string id_sesion, string modo, string valor) {
            return base.Channel.buscarCompradorPorAsync(id_sesion, modo, valor);
        }
        
        public string eliminaComprador(string id_sesion, string id_comprador) {
            return base.Channel.eliminaComprador(id_sesion, id_comprador);
        }
        
        public System.Threading.Tasks.Task<string> eliminaCompradorAsync(string id_sesion, string id_comprador) {
            return base.Channel.eliminaCompradorAsync(id_sesion, id_comprador);
        }
        
        public string registraventa(string id_sesion, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio) {
            return base.Channel.registraventa(id_sesion, comprador, vendedor, lote, total_venta, saldo_actual, mensualidades, pago, pago_minimo, fecha_alta, fecha_corte, tipo_pago, comicion, interes_tardio);
        }
        
        public System.Threading.Tasks.Task<string> registraventaAsync(string id_sesion, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio) {
            return base.Channel.registraventaAsync(id_sesion, comprador, vendedor, lote, total_venta, saldo_actual, mensualidades, pago, pago_minimo, fecha_alta, fecha_corte, tipo_pago, comicion, interes_tardio);
        }
        
        public string updateVenta(string id_sesion, string id_venta, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio) {
            return base.Channel.updateVenta(id_sesion, id_venta, comprador, vendedor, lote, total_venta, saldo_actual, mensualidades, pago, pago_minimo, fecha_alta, fecha_corte, tipo_pago, comicion, interes_tardio);
        }
        
        public System.Threading.Tasks.Task<string> updateVentaAsync(string id_sesion, string id_venta, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio) {
            return base.Channel.updateVentaAsync(id_sesion, id_venta, comprador, vendedor, lote, total_venta, saldo_actual, mensualidades, pago, pago_minimo, fecha_alta, fecha_corte, tipo_pago, comicion, interes_tardio);
        }
        
        public string listaVentas(string id_sesion) {
            return base.Channel.listaVentas(id_sesion);
        }
        
        public System.Threading.Tasks.Task<string> listaVentasAsync(string id_sesion) {
            return base.Channel.listaVentasAsync(id_sesion);
        }
        
        public string getComision(string id_sesion, string venta) {
            return base.Channel.getComision(id_sesion, venta);
        }
        
        public System.Threading.Tasks.Task<string> getComisionAsync(string id_sesion, string venta) {
            return base.Channel.getComisionAsync(id_sesion, venta);
        }
        
        public string setComision(string id_sesion, string venta, string comicion) {
            return base.Channel.setComision(id_sesion, venta, comicion);
        }
        
        public System.Threading.Tasks.Task<string> setComisionAsync(string id_sesion, string venta, string comicion) {
            return base.Channel.setComisionAsync(id_sesion, venta, comicion);
        }
        
        public string getVenta(string id_sesion, string id_venta) {
            return base.Channel.getVenta(id_sesion, id_venta);
        }
        
        public System.Threading.Tasks.Task<string> getVentaAsync(string id_sesion, string id_venta) {
            return base.Channel.getVentaAsync(id_sesion, id_venta);
        }
        
        public string buscarVentaPor(string id_sesion, string modo, string valor) {
            return base.Channel.buscarVentaPor(id_sesion, modo, valor);
        }
        
        public System.Threading.Tasks.Task<string> buscarVentaPorAsync(string id_sesion, string modo, string valor) {
            return base.Channel.buscarVentaPorAsync(id_sesion, modo, valor);
        }
        
        public string registraLote(string id_sesion, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste) {
            return base.Channel.registraLote(id_sesion, pk_manzana, estatus, n_lote, descripcion, precio, medida, pk_norte, pk_sur, pk_este, pk_oeste);
        }
        
        public System.Threading.Tasks.Task<string> registraLoteAsync(string id_sesion, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste) {
            return base.Channel.registraLoteAsync(id_sesion, pk_manzana, estatus, n_lote, descripcion, precio, medida, pk_norte, pk_sur, pk_este, pk_oeste);
        }
        
        public string updateLote(string id_sesion, string id_lote, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste) {
            return base.Channel.updateLote(id_sesion, id_lote, pk_manzana, estatus, n_lote, descripcion, precio, medida, pk_norte, pk_sur, pk_este, pk_oeste);
        }
        
        public System.Threading.Tasks.Task<string> updateLoteAsync(string id_sesion, string id_lote, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste) {
            return base.Channel.updateLoteAsync(id_sesion, id_lote, pk_manzana, estatus, n_lote, descripcion, precio, medida, pk_norte, pk_sur, pk_este, pk_oeste);
        }
        
        public string eliminaLote(string id_sesion, string id_lote) {
            return base.Channel.eliminaLote(id_sesion, id_lote);
        }
        
        public System.Threading.Tasks.Task<string> eliminaLoteAsync(string id_sesion, string id_lote) {
            return base.Channel.eliminaLoteAsync(id_sesion, id_lote);
        }
        
        public string buscaLotePor(string id_sesion, string modo, string valor) {
            return base.Channel.buscaLotePor(id_sesion, modo, valor);
        }
        
        public System.Threading.Tasks.Task<string> buscaLotePorAsync(string id_sesion, string modo, string valor) {
            return base.Channel.buscaLotePorAsync(id_sesion, modo, valor);
        }
        
        public string hacerPago(string id_sesion, string id_venta) {
            return base.Channel.hacerPago(id_sesion, id_venta);
        }
        
        public System.Threading.Tasks.Task<string> hacerPagoAsync(string id_sesion, string id_venta) {
            return base.Channel.hacerPagoAsync(id_sesion, id_venta);
        }
        
        public string cancelarPago(string id_sesion, string id_venta) {
            return base.Channel.cancelarPago(id_sesion, id_venta);
        }
        
        public System.Threading.Tasks.Task<string> cancelarPagoAsync(string id_sesion, string id_venta) {
            return base.Channel.cancelarPagoAsync(id_sesion, id_venta);
        }
        
        public string buscarPagos(string id_sesion, string modo, string valor) {
            return base.Channel.buscarPagos(id_sesion, modo, valor);
        }
        
        public System.Threading.Tasks.Task<string> buscarPagosAsync(string id_sesion, string modo, string valor) {
            return base.Channel.buscarPagosAsync(id_sesion, modo, valor);
        }
    }
}
