//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34003
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.34003.
// 
#pragma warning disable 1591

namespace PvTerrenos.WSpvt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PVTBinding", Namespace="http://serviciodeconsultas.hol.es/webservice/")]
    public partial class PVT : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarUsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback usuarioUpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback usuarioChangePasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPerfilUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarUsuarioPorOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraCompradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateCompradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCompradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback listarCompradoresOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarCompradorPorOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminaCompradorOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraventaOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback listaVentasOperationCompleted;
        
        private System.Threading.SendOrPostCallback getComisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback setComisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVentaOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarVentaPorOperationCompleted;
        
        private System.Threading.SendOrPostCallback registraLoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback updateLoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback eliminaLoteOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscaLotePorOperationCompleted;
        
        private System.Threading.SendOrPostCallback hacerPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback buscarPagosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PVT() {
            this.Url = global::PvTerrenos.Properties.Settings.Default.PvTerrenos_WSpvt_PVT;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event registraUsuarioCompletedEventHandler registraUsuarioCompleted;
        
        /// <remarks/>
        public event listarUsuariosCompletedEventHandler listarUsuariosCompleted;
        
        /// <remarks/>
        public event usuarioUpdateCompletedEventHandler usuarioUpdateCompleted;
        
        /// <remarks/>
        public event usuarioChangePasswordCompletedEventHandler usuarioChangePasswordCompleted;
        
        /// <remarks/>
        public event getPerfilUsuarioCompletedEventHandler getPerfilUsuarioCompleted;
        
        /// <remarks/>
        public event buscarUsuarioPorCompletedEventHandler buscarUsuarioPorCompleted;
        
        /// <remarks/>
        public event registraCompradorCompletedEventHandler registraCompradorCompleted;
        
        /// <remarks/>
        public event updateCompradorCompletedEventHandler updateCompradorCompleted;
        
        /// <remarks/>
        public event getCompradorCompletedEventHandler getCompradorCompleted;
        
        /// <remarks/>
        public event listarCompradoresCompletedEventHandler listarCompradoresCompleted;
        
        /// <remarks/>
        public event buscarCompradorPorCompletedEventHandler buscarCompradorPorCompleted;
        
        /// <remarks/>
        public event eliminaCompradorCompletedEventHandler eliminaCompradorCompleted;
        
        /// <remarks/>
        public event registraventaCompletedEventHandler registraventaCompleted;
        
        /// <remarks/>
        public event updateVentaCompletedEventHandler updateVentaCompleted;
        
        /// <remarks/>
        public event listaVentasCompletedEventHandler listaVentasCompleted;
        
        /// <remarks/>
        public event getComisionCompletedEventHandler getComisionCompleted;
        
        /// <remarks/>
        public event setComisionCompletedEventHandler setComisionCompleted;
        
        /// <remarks/>
        public event getVentaCompletedEventHandler getVentaCompleted;
        
        /// <remarks/>
        public event buscarVentaPorCompletedEventHandler buscarVentaPorCompleted;
        
        /// <remarks/>
        public event registraLoteCompletedEventHandler registraLoteCompleted;
        
        /// <remarks/>
        public event updateLoteCompletedEventHandler updateLoteCompleted;
        
        /// <remarks/>
        public event eliminaLoteCompletedEventHandler eliminaLoteCompleted;
        
        /// <remarks/>
        public event buscaLotePorCompletedEventHandler buscaLotePorCompleted;
        
        /// <remarks/>
        public event hacerPagoCompletedEventHandler hacerPagoCompleted;
        
        /// <remarks/>
        public event cancelarPagoCompletedEventHandler cancelarPagoCompleted;
        
        /// <remarks/>
        public event buscarPagosCompletedEventHandler buscarPagosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/login", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string login(string usuario, string password) {
            object[] results = this.Invoke("login", new object[] {
                        usuario,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string usuario, string password) {
            this.loginAsync(usuario, password, null);
        }
        
        /// <remarks/>
        public void loginAsync(string usuario, string password, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        usuario,
                        password}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraUsuario", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string registraUsuario(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email, string password) {
            object[] results = this.Invoke("registraUsuario", new object[] {
                        id_sesion,
                        nombre,
                        apellidoPaterno,
                        apellidoMaterno,
                        tipo,
                        email,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registraUsuarioAsync(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email, string password) {
            this.registraUsuarioAsync(id_sesion, nombre, apellidoPaterno, apellidoMaterno, tipo, email, password, null);
        }
        
        /// <remarks/>
        public void registraUsuarioAsync(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email, string password, object userState) {
            if ((this.registraUsuarioOperationCompleted == null)) {
                this.registraUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraUsuarioOperationCompleted);
            }
            this.InvokeAsync("registraUsuario", new object[] {
                        id_sesion,
                        nombre,
                        apellidoPaterno,
                        apellidoMaterno,
                        tipo,
                        email,
                        password}, this.registraUsuarioOperationCompleted, userState);
        }
        
        private void OnregistraUsuarioOperationCompleted(object arg) {
            if ((this.registraUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraUsuarioCompleted(this, new registraUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listarUsuarios", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string listarUsuarios(string id_sesion) {
            object[] results = this.Invoke("listarUsuarios", new object[] {
                        id_sesion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void listarUsuariosAsync(string id_sesion) {
            this.listarUsuariosAsync(id_sesion, null);
        }
        
        /// <remarks/>
        public void listarUsuariosAsync(string id_sesion, object userState) {
            if ((this.listarUsuariosOperationCompleted == null)) {
                this.listarUsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarUsuariosOperationCompleted);
            }
            this.InvokeAsync("listarUsuarios", new object[] {
                        id_sesion}, this.listarUsuariosOperationCompleted, userState);
        }
        
        private void OnlistarUsuariosOperationCompleted(object arg) {
            if ((this.listarUsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarUsuariosCompleted(this, new listarUsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/usuarioUpdate", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string usuarioUpdate(string id_sesion, string id_usuario, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email) {
            object[] results = this.Invoke("usuarioUpdate", new object[] {
                        id_sesion,
                        id_usuario,
                        nombre,
                        apellidoPaterno,
                        apellidoMaterno,
                        tipo,
                        email});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void usuarioUpdateAsync(string id_sesion, string id_usuario, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email) {
            this.usuarioUpdateAsync(id_sesion, id_usuario, nombre, apellidoPaterno, apellidoMaterno, tipo, email, null);
        }
        
        /// <remarks/>
        public void usuarioUpdateAsync(string id_sesion, string id_usuario, string nombre, string apellidoPaterno, string apellidoMaterno, string tipo, string email, object userState) {
            if ((this.usuarioUpdateOperationCompleted == null)) {
                this.usuarioUpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnusuarioUpdateOperationCompleted);
            }
            this.InvokeAsync("usuarioUpdate", new object[] {
                        id_sesion,
                        id_usuario,
                        nombre,
                        apellidoPaterno,
                        apellidoMaterno,
                        tipo,
                        email}, this.usuarioUpdateOperationCompleted, userState);
        }
        
        private void OnusuarioUpdateOperationCompleted(object arg) {
            if ((this.usuarioUpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.usuarioUpdateCompleted(this, new usuarioUpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/usuarioChangePasswor" +
            "d", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string usuarioChangePassword([System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion, string id_usuario, string password) {
            object[] results = this.Invoke("usuarioChangePassword", new object[] {
                        idsesion,
                        id_usuario,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void usuarioChangePasswordAsync(string idsesion, string id_usuario, string password) {
            this.usuarioChangePasswordAsync(idsesion, id_usuario, password, null);
        }
        
        /// <remarks/>
        public void usuarioChangePasswordAsync(string idsesion, string id_usuario, string password, object userState) {
            if ((this.usuarioChangePasswordOperationCompleted == null)) {
                this.usuarioChangePasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnusuarioChangePasswordOperationCompleted);
            }
            this.InvokeAsync("usuarioChangePassword", new object[] {
                        idsesion,
                        id_usuario,
                        password}, this.usuarioChangePasswordOperationCompleted, userState);
        }
        
        private void OnusuarioChangePasswordOperationCompleted(object arg) {
            if ((this.usuarioChangePasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.usuarioChangePasswordCompleted(this, new usuarioChangePasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getPerfilUsuario", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getPerfilUsuario([System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion) {
            object[] results = this.Invoke("getPerfilUsuario", new object[] {
                        idsesion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getPerfilUsuarioAsync(string idsesion) {
            this.getPerfilUsuarioAsync(idsesion, null);
        }
        
        /// <remarks/>
        public void getPerfilUsuarioAsync(string idsesion, object userState) {
            if ((this.getPerfilUsuarioOperationCompleted == null)) {
                this.getPerfilUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPerfilUsuarioOperationCompleted);
            }
            this.InvokeAsync("getPerfilUsuario", new object[] {
                        idsesion}, this.getPerfilUsuarioOperationCompleted, userState);
        }
        
        private void OngetPerfilUsuarioOperationCompleted(object arg) {
            if ((this.getPerfilUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPerfilUsuarioCompleted(this, new getPerfilUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarUsuarioPor", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string buscarUsuarioPor([System.Xml.Serialization.SoapElementAttribute("id-sesion")] string idsesion, string modo, string valor) {
            object[] results = this.Invoke("buscarUsuarioPor", new object[] {
                        idsesion,
                        modo,
                        valor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscarUsuarioPorAsync(string idsesion, string modo, string valor) {
            this.buscarUsuarioPorAsync(idsesion, modo, valor, null);
        }
        
        /// <remarks/>
        public void buscarUsuarioPorAsync(string idsesion, string modo, string valor, object userState) {
            if ((this.buscarUsuarioPorOperationCompleted == null)) {
                this.buscarUsuarioPorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarUsuarioPorOperationCompleted);
            }
            this.InvokeAsync("buscarUsuarioPor", new object[] {
                        idsesion,
                        modo,
                        valor}, this.buscarUsuarioPorOperationCompleted, userState);
        }
        
        private void OnbuscarUsuarioPorOperationCompleted(object arg) {
            if ((this.buscarUsuarioPorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarUsuarioPorCompleted(this, new buscarUsuarioPorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraComprador", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string registraComprador(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio) {
            object[] results = this.Invoke("registraComprador", new object[] {
                        id_sesion,
                        nombre,
                        apellidoPaterno,
                        apellidoMaterno,
                        domicilio,
                        recidencia,
                        e_civil,
                        ocupacion,
                        beneficiario,
                        tels,
                        colonia,
                        estado,
                        municipio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registraCompradorAsync(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio) {
            this.registraCompradorAsync(id_sesion, nombre, apellidoPaterno, apellidoMaterno, domicilio, recidencia, e_civil, ocupacion, beneficiario, tels, colonia, estado, municipio, null);
        }
        
        /// <remarks/>
        public void registraCompradorAsync(string id_sesion, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio, object userState) {
            if ((this.registraCompradorOperationCompleted == null)) {
                this.registraCompradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraCompradorOperationCompleted);
            }
            this.InvokeAsync("registraComprador", new object[] {
                        id_sesion,
                        nombre,
                        apellidoPaterno,
                        apellidoMaterno,
                        domicilio,
                        recidencia,
                        e_civil,
                        ocupacion,
                        beneficiario,
                        tels,
                        colonia,
                        estado,
                        municipio}, this.registraCompradorOperationCompleted, userState);
        }
        
        private void OnregistraCompradorOperationCompleted(object arg) {
            if ((this.registraCompradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraCompradorCompleted(this, new registraCompradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateComprador", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string updateComprador(string id_sesion, string id_comprador, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio) {
            object[] results = this.Invoke("updateComprador", new object[] {
                        id_sesion,
                        id_comprador,
                        nombre,
                        apellidoPaterno,
                        apellidoMaterno,
                        domicilio,
                        recidencia,
                        e_civil,
                        ocupacion,
                        beneficiario,
                        tels,
                        colonia,
                        estado,
                        municipio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateCompradorAsync(string id_sesion, string id_comprador, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio) {
            this.updateCompradorAsync(id_sesion, id_comprador, nombre, apellidoPaterno, apellidoMaterno, domicilio, recidencia, e_civil, ocupacion, beneficiario, tels, colonia, estado, municipio, null);
        }
        
        /// <remarks/>
        public void updateCompradorAsync(string id_sesion, string id_comprador, string nombre, string apellidoPaterno, string apellidoMaterno, string domicilio, string recidencia, string e_civil, string ocupacion, string beneficiario, string tels, string colonia, string estado, string municipio, object userState) {
            if ((this.updateCompradorOperationCompleted == null)) {
                this.updateCompradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateCompradorOperationCompleted);
            }
            this.InvokeAsync("updateComprador", new object[] {
                        id_sesion,
                        id_comprador,
                        nombre,
                        apellidoPaterno,
                        apellidoMaterno,
                        domicilio,
                        recidencia,
                        e_civil,
                        ocupacion,
                        beneficiario,
                        tels,
                        colonia,
                        estado,
                        municipio}, this.updateCompradorOperationCompleted, userState);
        }
        
        private void OnupdateCompradorOperationCompleted(object arg) {
            if ((this.updateCompradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateCompradorCompleted(this, new updateCompradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getComprador", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getComprador(string id_sesion, string id_comprador) {
            object[] results = this.Invoke("getComprador", new object[] {
                        id_sesion,
                        id_comprador});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCompradorAsync(string id_sesion, string id_comprador) {
            this.getCompradorAsync(id_sesion, id_comprador, null);
        }
        
        /// <remarks/>
        public void getCompradorAsync(string id_sesion, string id_comprador, object userState) {
            if ((this.getCompradorOperationCompleted == null)) {
                this.getCompradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCompradorOperationCompleted);
            }
            this.InvokeAsync("getComprador", new object[] {
                        id_sesion,
                        id_comprador}, this.getCompradorOperationCompleted, userState);
        }
        
        private void OngetCompradorOperationCompleted(object arg) {
            if ((this.getCompradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCompradorCompleted(this, new getCompradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listarCompradores", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string listarCompradores(string id_sesion) {
            object[] results = this.Invoke("listarCompradores", new object[] {
                        id_sesion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void listarCompradoresAsync(string id_sesion) {
            this.listarCompradoresAsync(id_sesion, null);
        }
        
        /// <remarks/>
        public void listarCompradoresAsync(string id_sesion, object userState) {
            if ((this.listarCompradoresOperationCompleted == null)) {
                this.listarCompradoresOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistarCompradoresOperationCompleted);
            }
            this.InvokeAsync("listarCompradores", new object[] {
                        id_sesion}, this.listarCompradoresOperationCompleted, userState);
        }
        
        private void OnlistarCompradoresOperationCompleted(object arg) {
            if ((this.listarCompradoresCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listarCompradoresCompleted(this, new listarCompradoresCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarCompradorPor", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string buscarCompradorPor(string id_sesion, string modo, string valor) {
            object[] results = this.Invoke("buscarCompradorPor", new object[] {
                        id_sesion,
                        modo,
                        valor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscarCompradorPorAsync(string id_sesion, string modo, string valor) {
            this.buscarCompradorPorAsync(id_sesion, modo, valor, null);
        }
        
        /// <remarks/>
        public void buscarCompradorPorAsync(string id_sesion, string modo, string valor, object userState) {
            if ((this.buscarCompradorPorOperationCompleted == null)) {
                this.buscarCompradorPorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarCompradorPorOperationCompleted);
            }
            this.InvokeAsync("buscarCompradorPor", new object[] {
                        id_sesion,
                        modo,
                        valor}, this.buscarCompradorPorOperationCompleted, userState);
        }
        
        private void OnbuscarCompradorPorOperationCompleted(object arg) {
            if ((this.buscarCompradorPorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarCompradorPorCompleted(this, new buscarCompradorPorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/eliminaComprador", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string eliminaComprador(string id_sesion, string id_comprador) {
            object[] results = this.Invoke("eliminaComprador", new object[] {
                        id_sesion,
                        id_comprador});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eliminaCompradorAsync(string id_sesion, string id_comprador) {
            this.eliminaCompradorAsync(id_sesion, id_comprador, null);
        }
        
        /// <remarks/>
        public void eliminaCompradorAsync(string id_sesion, string id_comprador, object userState) {
            if ((this.eliminaCompradorOperationCompleted == null)) {
                this.eliminaCompradorOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminaCompradorOperationCompleted);
            }
            this.InvokeAsync("eliminaComprador", new object[] {
                        id_sesion,
                        id_comprador}, this.eliminaCompradorOperationCompleted, userState);
        }
        
        private void OneliminaCompradorOperationCompleted(object arg) {
            if ((this.eliminaCompradorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminaCompradorCompleted(this, new eliminaCompradorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraventa", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string registraventa(string id_sesion, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio) {
            object[] results = this.Invoke("registraventa", new object[] {
                        id_sesion,
                        comprador,
                        vendedor,
                        lote,
                        total_venta,
                        saldo_actual,
                        mensualidades,
                        pago,
                        pago_minimo,
                        fecha_alta,
                        fecha_corte,
                        tipo_pago,
                        comicion,
                        interes_tardio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registraventaAsync(string id_sesion, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio) {
            this.registraventaAsync(id_sesion, comprador, vendedor, lote, total_venta, saldo_actual, mensualidades, pago, pago_minimo, fecha_alta, fecha_corte, tipo_pago, comicion, interes_tardio, null);
        }
        
        /// <remarks/>
        public void registraventaAsync(string id_sesion, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio, object userState) {
            if ((this.registraventaOperationCompleted == null)) {
                this.registraventaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraventaOperationCompleted);
            }
            this.InvokeAsync("registraventa", new object[] {
                        id_sesion,
                        comprador,
                        vendedor,
                        lote,
                        total_venta,
                        saldo_actual,
                        mensualidades,
                        pago,
                        pago_minimo,
                        fecha_alta,
                        fecha_corte,
                        tipo_pago,
                        comicion,
                        interes_tardio}, this.registraventaOperationCompleted, userState);
        }
        
        private void OnregistraventaOperationCompleted(object arg) {
            if ((this.registraventaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraventaCompleted(this, new registraventaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateVenta", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string updateVenta(string id_sesion, string id_venta, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio) {
            object[] results = this.Invoke("updateVenta", new object[] {
                        id_sesion,
                        id_venta,
                        comprador,
                        vendedor,
                        lote,
                        total_venta,
                        saldo_actual,
                        mensualidades,
                        pago,
                        pago_minimo,
                        fecha_alta,
                        fecha_corte,
                        tipo_pago,
                        comicion,
                        interes_tardio});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateVentaAsync(string id_sesion, string id_venta, string comprador, string vendedor, string lote, string total_venta, string saldo_actual, string mensualidades, string pago, string pago_minimo, string fecha_alta, string fecha_corte, string tipo_pago, string comicion, string interes_tardio) {
            this.updateVentaAsync(id_sesion, id_venta, comprador, vendedor, lote, total_venta, saldo_actual, mensualidades, pago, pago_minimo, fecha_alta, fecha_corte, tipo_pago, comicion, interes_tardio, null);
        }
        
        /// <remarks/>
        public void updateVentaAsync(
                    string id_sesion, 
                    string id_venta, 
                    string comprador, 
                    string vendedor, 
                    string lote, 
                    string total_venta, 
                    string saldo_actual, 
                    string mensualidades, 
                    string pago, 
                    string pago_minimo, 
                    string fecha_alta, 
                    string fecha_corte, 
                    string tipo_pago, 
                    string comicion, 
                    string interes_tardio, 
                    object userState) {
            if ((this.updateVentaOperationCompleted == null)) {
                this.updateVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateVentaOperationCompleted);
            }
            this.InvokeAsync("updateVenta", new object[] {
                        id_sesion,
                        id_venta,
                        comprador,
                        vendedor,
                        lote,
                        total_venta,
                        saldo_actual,
                        mensualidades,
                        pago,
                        pago_minimo,
                        fecha_alta,
                        fecha_corte,
                        tipo_pago,
                        comicion,
                        interes_tardio}, this.updateVentaOperationCompleted, userState);
        }
        
        private void OnupdateVentaOperationCompleted(object arg) {
            if ((this.updateVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateVentaCompleted(this, new updateVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/listaVentas", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string listaVentas(string id_sesion) {
            object[] results = this.Invoke("listaVentas", new object[] {
                        id_sesion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void listaVentasAsync(string id_sesion) {
            this.listaVentasAsync(id_sesion, null);
        }
        
        /// <remarks/>
        public void listaVentasAsync(string id_sesion, object userState) {
            if ((this.listaVentasOperationCompleted == null)) {
                this.listaVentasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlistaVentasOperationCompleted);
            }
            this.InvokeAsync("listaVentas", new object[] {
                        id_sesion}, this.listaVentasOperationCompleted, userState);
        }
        
        private void OnlistaVentasOperationCompleted(object arg) {
            if ((this.listaVentasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.listaVentasCompleted(this, new listaVentasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getComision", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getComision(string id_sesion, string venta) {
            object[] results = this.Invoke("getComision", new object[] {
                        id_sesion,
                        venta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getComisionAsync(string id_sesion, string venta) {
            this.getComisionAsync(id_sesion, venta, null);
        }
        
        /// <remarks/>
        public void getComisionAsync(string id_sesion, string venta, object userState) {
            if ((this.getComisionOperationCompleted == null)) {
                this.getComisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetComisionOperationCompleted);
            }
            this.InvokeAsync("getComision", new object[] {
                        id_sesion,
                        venta}, this.getComisionOperationCompleted, userState);
        }
        
        private void OngetComisionOperationCompleted(object arg) {
            if ((this.getComisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getComisionCompleted(this, new getComisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/setComision", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string setComision(string id_sesion, string venta, string comicion) {
            object[] results = this.Invoke("setComision", new object[] {
                        id_sesion,
                        venta,
                        comicion});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setComisionAsync(string id_sesion, string venta, string comicion) {
            this.setComisionAsync(id_sesion, venta, comicion, null);
        }
        
        /// <remarks/>
        public void setComisionAsync(string id_sesion, string venta, string comicion, object userState) {
            if ((this.setComisionOperationCompleted == null)) {
                this.setComisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetComisionOperationCompleted);
            }
            this.InvokeAsync("setComision", new object[] {
                        id_sesion,
                        venta,
                        comicion}, this.setComisionOperationCompleted, userState);
        }
        
        private void OnsetComisionOperationCompleted(object arg) {
            if ((this.setComisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setComisionCompleted(this, new setComisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/getVenta", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string getVenta(string id_sesion, string id_venta) {
            object[] results = this.Invoke("getVenta", new object[] {
                        id_sesion,
                        id_venta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVentaAsync(string id_sesion, string id_venta) {
            this.getVentaAsync(id_sesion, id_venta, null);
        }
        
        /// <remarks/>
        public void getVentaAsync(string id_sesion, string id_venta, object userState) {
            if ((this.getVentaOperationCompleted == null)) {
                this.getVentaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVentaOperationCompleted);
            }
            this.InvokeAsync("getVenta", new object[] {
                        id_sesion,
                        id_venta}, this.getVentaOperationCompleted, userState);
        }
        
        private void OngetVentaOperationCompleted(object arg) {
            if ((this.getVentaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVentaCompleted(this, new getVentaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarVentaPor", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string buscarVentaPor(string id_sesion, string modo, string valor) {
            object[] results = this.Invoke("buscarVentaPor", new object[] {
                        id_sesion,
                        modo,
                        valor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscarVentaPorAsync(string id_sesion, string modo, string valor) {
            this.buscarVentaPorAsync(id_sesion, modo, valor, null);
        }
        
        /// <remarks/>
        public void buscarVentaPorAsync(string id_sesion, string modo, string valor, object userState) {
            if ((this.buscarVentaPorOperationCompleted == null)) {
                this.buscarVentaPorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarVentaPorOperationCompleted);
            }
            this.InvokeAsync("buscarVentaPor", new object[] {
                        id_sesion,
                        modo,
                        valor}, this.buscarVentaPorOperationCompleted, userState);
        }
        
        private void OnbuscarVentaPorOperationCompleted(object arg) {
            if ((this.buscarVentaPorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarVentaPorCompleted(this, new buscarVentaPorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/registraLote", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string registraLote(string id_sesion, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste) {
            object[] results = this.Invoke("registraLote", new object[] {
                        id_sesion,
                        pk_manzana,
                        estatus,
                        n_lote,
                        descripcion,
                        precio,
                        medida,
                        pk_norte,
                        pk_sur,
                        pk_este,
                        pk_oeste});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void registraLoteAsync(string id_sesion, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste) {
            this.registraLoteAsync(id_sesion, pk_manzana, estatus, n_lote, descripcion, precio, medida, pk_norte, pk_sur, pk_este, pk_oeste, null);
        }
        
        /// <remarks/>
        public void registraLoteAsync(string id_sesion, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste, object userState) {
            if ((this.registraLoteOperationCompleted == null)) {
                this.registraLoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnregistraLoteOperationCompleted);
            }
            this.InvokeAsync("registraLote", new object[] {
                        id_sesion,
                        pk_manzana,
                        estatus,
                        n_lote,
                        descripcion,
                        precio,
                        medida,
                        pk_norte,
                        pk_sur,
                        pk_este,
                        pk_oeste}, this.registraLoteOperationCompleted, userState);
        }
        
        private void OnregistraLoteOperationCompleted(object arg) {
            if ((this.registraLoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.registraLoteCompleted(this, new registraLoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/updateLote", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string updateLote(string id_sesion, string id_lote, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste) {
            object[] results = this.Invoke("updateLote", new object[] {
                        id_sesion,
                        id_lote,
                        pk_manzana,
                        estatus,
                        n_lote,
                        descripcion,
                        precio,
                        medida,
                        pk_norte,
                        pk_sur,
                        pk_este,
                        pk_oeste});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void updateLoteAsync(string id_sesion, string id_lote, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste) {
            this.updateLoteAsync(id_sesion, id_lote, pk_manzana, estatus, n_lote, descripcion, precio, medida, pk_norte, pk_sur, pk_este, pk_oeste, null);
        }
        
        /// <remarks/>
        public void updateLoteAsync(string id_sesion, string id_lote, string pk_manzana, string estatus, string n_lote, string descripcion, string precio, string medida, string pk_norte, string pk_sur, string pk_este, string pk_oeste, object userState) {
            if ((this.updateLoteOperationCompleted == null)) {
                this.updateLoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnupdateLoteOperationCompleted);
            }
            this.InvokeAsync("updateLote", new object[] {
                        id_sesion,
                        id_lote,
                        pk_manzana,
                        estatus,
                        n_lote,
                        descripcion,
                        precio,
                        medida,
                        pk_norte,
                        pk_sur,
                        pk_este,
                        pk_oeste}, this.updateLoteOperationCompleted, userState);
        }
        
        private void OnupdateLoteOperationCompleted(object arg) {
            if ((this.updateLoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.updateLoteCompleted(this, new updateLoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/eliminaLote", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string eliminaLote(string id_sesion, string id_lote) {
            object[] results = this.Invoke("eliminaLote", new object[] {
                        id_sesion,
                        id_lote});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void eliminaLoteAsync(string id_sesion, string id_lote) {
            this.eliminaLoteAsync(id_sesion, id_lote, null);
        }
        
        /// <remarks/>
        public void eliminaLoteAsync(string id_sesion, string id_lote, object userState) {
            if ((this.eliminaLoteOperationCompleted == null)) {
                this.eliminaLoteOperationCompleted = new System.Threading.SendOrPostCallback(this.OneliminaLoteOperationCompleted);
            }
            this.InvokeAsync("eliminaLote", new object[] {
                        id_sesion,
                        id_lote}, this.eliminaLoteOperationCompleted, userState);
        }
        
        private void OneliminaLoteOperationCompleted(object arg) {
            if ((this.eliminaLoteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.eliminaLoteCompleted(this, new eliminaLoteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscaLotePor", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string buscaLotePor(string id_sesion, string modo, string valor) {
            object[] results = this.Invoke("buscaLotePor", new object[] {
                        id_sesion,
                        modo,
                        valor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscaLotePorAsync(string id_sesion, string modo, string valor) {
            this.buscaLotePorAsync(id_sesion, modo, valor, null);
        }
        
        /// <remarks/>
        public void buscaLotePorAsync(string id_sesion, string modo, string valor, object userState) {
            if ((this.buscaLotePorOperationCompleted == null)) {
                this.buscaLotePorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscaLotePorOperationCompleted);
            }
            this.InvokeAsync("buscaLotePor", new object[] {
                        id_sesion,
                        modo,
                        valor}, this.buscaLotePorOperationCompleted, userState);
        }
        
        private void OnbuscaLotePorOperationCompleted(object arg) {
            if ((this.buscaLotePorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscaLotePorCompleted(this, new buscaLotePorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/hacerPago", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string hacerPago(string id_sesion, string id_venta) {
            object[] results = this.Invoke("hacerPago", new object[] {
                        id_sesion,
                        id_venta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void hacerPagoAsync(string id_sesion, string id_venta) {
            this.hacerPagoAsync(id_sesion, id_venta, null);
        }
        
        /// <remarks/>
        public void hacerPagoAsync(string id_sesion, string id_venta, object userState) {
            if ((this.hacerPagoOperationCompleted == null)) {
                this.hacerPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnhacerPagoOperationCompleted);
            }
            this.InvokeAsync("hacerPago", new object[] {
                        id_sesion,
                        id_venta}, this.hacerPagoOperationCompleted, userState);
        }
        
        private void OnhacerPagoOperationCompleted(object arg) {
            if ((this.hacerPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.hacerPagoCompleted(this, new hacerPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/cancelarPago", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string cancelarPago(string id_sesion, string id_venta) {
            object[] results = this.Invoke("cancelarPago", new object[] {
                        id_sesion,
                        id_venta});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarPagoAsync(string id_sesion, string id_venta) {
            this.cancelarPagoAsync(id_sesion, id_venta, null);
        }
        
        /// <remarks/>
        public void cancelarPagoAsync(string id_sesion, string id_venta, object userState) {
            if ((this.cancelarPagoOperationCompleted == null)) {
                this.cancelarPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarPagoOperationCompleted);
            }
            this.InvokeAsync("cancelarPago", new object[] {
                        id_sesion,
                        id_venta}, this.cancelarPagoOperationCompleted, userState);
        }
        
        private void OncancelarPagoOperationCompleted(object arg) {
            if ((this.cancelarPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarPagoCompleted(this, new cancelarPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://serviciodeconsultas.hol.es/webservice/pvt-webserv.php/buscarPagos", RequestNamespace="http://serviciodeconsultas.hol.es/webservice/", ResponseNamespace="http://serviciodeconsultas.hol.es/webservice/")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string buscarPagos(string id_sesion, string modo, string valor) {
            object[] results = this.Invoke("buscarPagos", new object[] {
                        id_sesion,
                        modo,
                        valor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void buscarPagosAsync(string id_sesion, string modo, string valor) {
            this.buscarPagosAsync(id_sesion, modo, valor, null);
        }
        
        /// <remarks/>
        public void buscarPagosAsync(string id_sesion, string modo, string valor, object userState) {
            if ((this.buscarPagosOperationCompleted == null)) {
                this.buscarPagosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbuscarPagosOperationCompleted);
            }
            this.InvokeAsync("buscarPagos", new object[] {
                        id_sesion,
                        modo,
                        valor}, this.buscarPagosOperationCompleted, userState);
        }
        
        private void OnbuscarPagosOperationCompleted(object arg) {
            if ((this.buscarPagosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.buscarPagosCompleted(this, new buscarPagosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void registraUsuarioCompletedEventHandler(object sender, registraUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listarUsuariosCompletedEventHandler(object sender, listarUsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarUsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarUsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void usuarioUpdateCompletedEventHandler(object sender, usuarioUpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class usuarioUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal usuarioUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void usuarioChangePasswordCompletedEventHandler(object sender, usuarioChangePasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class usuarioChangePasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal usuarioChangePasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getPerfilUsuarioCompletedEventHandler(object sender, getPerfilUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPerfilUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPerfilUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void buscarUsuarioPorCompletedEventHandler(object sender, buscarUsuarioPorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarUsuarioPorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarUsuarioPorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void registraCompradorCompletedEventHandler(object sender, registraCompradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraCompradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraCompradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void updateCompradorCompletedEventHandler(object sender, updateCompradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateCompradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateCompradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getCompradorCompletedEventHandler(object sender, getCompradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCompradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCompradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listarCompradoresCompletedEventHandler(object sender, listarCompradoresCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listarCompradoresCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listarCompradoresCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void buscarCompradorPorCompletedEventHandler(object sender, buscarCompradorPorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarCompradorPorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarCompradorPorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void eliminaCompradorCompletedEventHandler(object sender, eliminaCompradorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminaCompradorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminaCompradorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void registraventaCompletedEventHandler(object sender, registraventaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraventaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraventaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /*public registraventaCompletedEventArgs()
        {
            // TODO: Complete member initialization
        }*/
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void updateVentaCompletedEventHandler(object sender, updateVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void listaVentasCompletedEventHandler(object sender, listaVentasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class listaVentasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal listaVentasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getComisionCompletedEventHandler(object sender, getComisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getComisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getComisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void setComisionCompletedEventHandler(object sender, setComisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setComisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setComisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void getVentaCompletedEventHandler(object sender, getVentaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVentaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVentaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void buscarVentaPorCompletedEventHandler(object sender, buscarVentaPorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarVentaPorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarVentaPorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void registraLoteCompletedEventHandler(object sender, registraLoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class registraLoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal registraLoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void updateLoteCompletedEventHandler(object sender, updateLoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class updateLoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal updateLoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void eliminaLoteCompletedEventHandler(object sender, eliminaLoteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class eliminaLoteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal eliminaLoteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void buscaLotePorCompletedEventHandler(object sender, buscaLotePorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscaLotePorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscaLotePorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void hacerPagoCompletedEventHandler(object sender, hacerPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hacerPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal hacerPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void cancelarPagoCompletedEventHandler(object sender, cancelarPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    public delegate void buscarPagosCompletedEventHandler(object sender, buscarPagosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class buscarPagosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal buscarPagosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591